version: '3'
services:
  php_worker:
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    container_name: php_worker
    restart: unless-stopped
    depends_on:
      rabbitmq:
        condition: service_healthy
      mysql:
        condition: service_healthy

  rabbitmq:
    build:
      context: ./docker/rabbitmq
      dockerfile: Dockerfile
    container_name: rabbitmq
    restart: unless-stopped
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 2
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - "8080:15672"
      - "5672:5672"
      - "25672:25672"

  mysql:
    image: mysql:8.0.31
    container_name: mysql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 2
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"      